[package]
name = "video_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
kaze = { git = "https://github.com/yupferris/kaze" }
rtl = { path = "../../rtl" }
